@Host = http://localhost:3000

### 1. Registrar Usuario Nuevo
POST {{Host}}/auth/register
Content-Type: application/json

{
  "name": "Alex",
  "email": "alex@test.com",
  "password": "password123"
}

### 2. Iniciar Sesión (Debería devolver un access_token)
POST {{Host}}/auth/login
Content-Type: application/json

{
  "email": "alex@test.com",
  "password": "password123"
}

### Crear Gasto (Asegúrate que categoryId exista)
POST {{Host}}/transactions
Content-Type: application/json

{
  "amount": 150.50,
  "concept": "Hamburguesas",
  "date": "2026-01-30T20:00:00Z",
  "type": "EXPENSE",
  "categoryId": 3
}

### Ver Transacciones
GET {{Host}}/transactions

### 1. Obtener todas las categorías
GET {{Host}}/categories

### 2. Crear una nueva categoría
POST {{Host}}/categories
Content-Type: application/json

{
  "name": "Videojuegos",
  "icon": "🎮"
}

### 3. Intentar crear una duplicada (Para probar el error 409)
POST {{Host}}/categories
Content-Type: application/json

{
  "name": "Videojuegos",
  "icon": "🎮"
}

### 4. Actualizar una categoría (Cambia el ID '1' por el que quieras probar)
PATCH {{Host}}/categories/1
Content-Type: application/json

{
  "name": "Gaming Setup"
}

### 5. Borrar una categoría
DELETE {{Host}}/categories/1